// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { config } from "dotenv";
import { existsSync } from "fs";
import { join } from "path";

// Manually load environment variables since Prisma 7 might not automatically
// pick up .env.development or .env.production without explicit configuration.
const envPath = existsSync(join(process.cwd(), ".env.development"))
  ? join(process.cwd(), ".env.development")
  : existsSync(join(process.cwd(), ".env.production"))
    ? join(process.cwd(), ".env.production")
    : join(process.cwd(), ".env");

config({ path: envPath });

if (!process.env.DATABASE_URL) {
  console.warn(`Warning: DATABASE_URL not found in ${envPath}`);
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
