import { Injectable, NotFoundException } from '@nestjs/common';
import type { QuestResponse, QuestType } from '@scholarxp/api-contracts';
import { CreateDailyQuestDto } from './dto/create-daily-quest.dto';
import { UpdateDailyQuestDto } from './dto/update-daily-quest.dto';
import { PrismaService } from '../../prisma/prisma.service';

@Injectable()
export class DailyQuestService {
  constructor(private readonly prisma: PrismaService) {}

  // User-scoped history powers the quests page while keeping persistence details inside the backend.
  async listHistoryForUser(userId: number): Promise<QuestResponse> {
    const rows = await this.prisma.dailyQuest.findMany({
      where: { userId },
      include: {
        module: {
          select: {
            title: true,
          },
        },
      },
      orderBy: [{ questDateUtc: 'desc' }, { id: 'asc' }],
    });

    return {
      quests: rows.map((row) => ({
        id: row.id,
        moduleId: row.moduleId,
        moduleTitle: row.module.title,
        // Quest type values are generated by backend rules and are constrained by shared contracts.
        type: row.type as QuestType,
        expGranted: row.expGranted,
        isCompleted: row.isCompleted,
        // Date-only format keeps frontend grouping deterministic for UTC-day history.
        questDateUtc: row.questDateUtc.toISOString().slice(0, 10),
        generatedAt: row.generatedAt.toISOString(),
        completedAt: row.completedAt ? row.completedAt.toISOString() : null,
      })),
    };
  }

  create(createDailyQuestDto: CreateDailyQuestDto) {
    return this.prisma.dailyQuest.create({ data: createDailyQuestDto });
  }

  findAll() {
    return this.prisma.dailyQuest.findMany();
  }

  async findOne(id: number) {
    return this.getOrThrow(id);
  }

  async update(id: number, updateDailyQuestDto: UpdateDailyQuestDto) {
    await this.getOrThrow(id);
    return this.prisma.dailyQuest.update({
      where: { id },
      data: updateDailyQuestDto,
    });
  }

  async remove(id: number) {
    await this.getOrThrow(id);
    return this.prisma.dailyQuest.delete({ where: { id } });
  }

  private async getOrThrow(id: number) {
    const record = await this.prisma.dailyQuest.findUnique({ where: { id } });
    if (!record) {
      throw new NotFoundException(`DailyQuest ${id} not found`);
    }
    return record;
  }
}
