import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { QuestTypeValues, type QuestType } from '@scholarxp/api-contracts';
import { CreateDailyQuestDto } from './dto/create-daily-quest.dto';
import { UpdateDailyQuestDto } from './dto/update-daily-quest.dto';
import { GetQuestHistoryQueryDto } from './dto/get-quest-history-query.dto';
import {
  QuestHistoryItemDto,
  QuestHistoryResponseDto,
} from './dto/quest-history-response.dto';
import { PrismaService } from '../../prisma/prisma.service';

const DEFAULT_DAY_LIMIT = 14;
const DEFAULT_DAY_OFFSET = 0;

@Injectable()
export class DailyQuestService {
  constructor(private readonly prisma: PrismaService) {}

  // User-scoped history powers the quests page while keeping persistence details inside the backend.
  async listHistoryForUser(
    userId: number,
    query: GetQuestHistoryQueryDto,
  ): Promise<QuestHistoryResponseDto> {
    const dayLimit = normalizeDayLimit(query.dayLimit);
    const dayOffset = normalizeDayOffset(query.dayOffset);

    // ASk the database for only the requested page of distinct quest days (+1 to detect hasMore)
    const questDayGroups = await this.prisma.dailyQuest.groupBy({
      where: { userId },
      by: ['questDateUtc'],
      orderBy: { questDateUtc: 'desc' },
      skip: dayOffset,
      take: dayLimit + 1,
    });

    const hasMore = questDayGroups.length > dayLimit;
    const pagedQuestDays = questDayGroups
      .slice(0, dayLimit)
      .map((entry) => entry.questDateUtc);
    if (pagedQuestDays.length === 0) {
      return {
        quests: [],
        hasMore: false,
        nextDayOffset: null,
      };
    }

    const rows = await this.prisma.dailyQuest.findMany({
      where: {
        userId,
        questDateUtc: {
          in: pagedQuestDays,
        },
      },
      include: {
        module: {
          select: {
            title: true,
          },
        },
        moduleUnit: {
          select: {
            title: true,
          },
        },
      },
      orderBy: [{ questDateUtc: 'desc' }, { id: 'asc' }],
    });

    const nextOffset = dayOffset + dayLimit;

    return {
      quests: rows.map((row): QuestHistoryItemDto => {
        return {
          id: row.id,
          moduleId: row.moduleId,
          moduleUnitId: row.moduleUnitId,
          moduleTitle: row.module.title,
          moduleUnitTitle: row.moduleUnit?.title ?? null,
          // Quest type values are generated by backend rules and are constrained by shared contracts.
          type: row.type as QuestType,
          expGranted: row.expGranted,
          isCompleted: row.isCompleted,
          // Server-owned description keeps phrasing consistent across all clients.
          description: buildQuestDescription(
            row.type as QuestType,
            row.module.title,
            row.moduleUnit?.title ?? null,
          ),
          // Date-only format keeps frontend grouping deterministic for UTC-day history.
          questDateUtc: row.questDateUtc.toISOString().slice(0, 10),
          generatedAt: row.generatedAt.toISOString(),
          completedAt: row.completedAt ? row.completedAt.toISOString() : null,
        };
      }),
      hasMore,
      nextDayOffset: hasMore ? nextOffset : null,
    };
  }

  async create(createDailyQuestDto: CreateDailyQuestDto) {
    await this.assertValidQuestTarget({
      type: createDailyQuestDto.type,
      moduleId: createDailyQuestDto.moduleId,
      moduleUnitId: createDailyQuestDto.moduleUnitId ?? null,
    });

    return this.prisma.dailyQuest.create({ data: createDailyQuestDto });
  }

  findAll() {
    return this.prisma.dailyQuest.findMany();
  }

  async findOne(id: number) {
    return this.getOrThrow(id);
  }

  async update(id: number, updateDailyQuestDto: UpdateDailyQuestDto) {
    const existingQuest = await this.getOrThrow(id);
    const nextType = updateDailyQuestDto.type ?? existingQuest.type;
    const nextModuleId = updateDailyQuestDto.moduleId ?? existingQuest.moduleId;
    const nextModuleUnitId =
      updateDailyQuestDto.moduleUnitId !== undefined
        ? updateDailyQuestDto.moduleUnitId
        : existingQuest.moduleUnitId;

    await this.assertValidQuestTarget({
      type: nextType,
      moduleId: nextModuleId,
      moduleUnitId: nextModuleUnitId ?? null,
    });

    return this.prisma.dailyQuest.update({
      where: { id },
      data: updateDailyQuestDto,
    });
  }

  async remove(id: number) {
    await this.getOrThrow(id);
    return this.prisma.dailyQuest.delete({ where: { id } });
  }

  private async getOrThrow(id: number) {
    const record = await this.prisma.dailyQuest.findUnique({ where: { id } });
    if (!record) {
      throw new NotFoundException(`DailyQuest ${id} not found`);
    }
    return record;
  }

  private async assertValidQuestTarget(input: {
    type: string;
    moduleId: number;
    moduleUnitId: number | null;
  }): Promise<void> {
    const requiresUnitTarget = input.type === QuestTypeValues.completeNewUnit;
    if (requiresUnitTarget && input.moduleUnitId === null) {
      throw new BadRequestException(
        'A lesson target is required for complete_new_unit quests.',
      );
    }
    if (!requiresUnitTarget && input.moduleUnitId !== null) {
      throw new BadRequestException(
        'Only complete_new_unit quests can target a lesson.',
      );
    }
    if (input.moduleUnitId === null) {
      return;
    }

    // Keep quest targeting deterministic by requiring the linked lesson to exist under the same module.
    const targetUnit = await this.prisma.moduleUnit.findUnique({
      where: { id: input.moduleUnitId },
      select: { moduleId: true },
    });
    if (!targetUnit || targetUnit.moduleId === null) {
      throw new BadRequestException('The selected lesson was not found.');
    }
    if (targetUnit.moduleId !== input.moduleId) {
      throw new BadRequestException(
        'The selected lesson does not belong to the selected module.',
      );
    }
  }
}

function normalizeDayLimit(value: number | undefined): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    return DEFAULT_DAY_LIMIT;
  }
  return Math.max(1, Math.min(31, Math.floor(value)));
}

function normalizeDayOffset(value: number | undefined): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    return DEFAULT_DAY_OFFSET;
  }
  return Math.max(0, Math.floor(value));
}

function buildQuestDescription(
  type: QuestType,
  moduleTitle: string,
  moduleUnitTitle: string | null,
): string {
  if (type === QuestTypeValues.completeDailyPractice) {
    return `Complete the daily practice set for the ${moduleTitle} module.`;
  }
  if (type === QuestTypeValues.completeNewUnit) {
    if (moduleUnitTitle) {
      return `Complete all questions from the new '${moduleUnitTitle}' lesson of the ${moduleTitle} module.`;
    }
    return `Complete all questions from a new lesson in your ${moduleTitle} module.`;
  }
  // Defensive fallback for unexpected values from legacy rows.
  return `Complete your quest for the ${moduleTitle} module.`;
}
