import { Injectable, NotFoundException } from '@nestjs/common';
import type { QuestType } from '@scholarxp/api-contracts';
import { CreateDailyQuestDto } from './dto/create-daily-quest.dto';
import { UpdateDailyQuestDto } from './dto/update-daily-quest.dto';
import { GetQuestHistoryQueryDto } from './dto/get-quest-history-query.dto';
import {
  QuestHistoryItemDto,
  QuestHistoryResponseDto,
} from './dto/quest-history-response.dto';
import { PrismaService } from '../../prisma/prisma.service';

const DEFAULT_DAY_LIMIT = 14;
const DEFAULT_DAY_OFFSET = 0;

@Injectable()
export class DailyQuestService {
  constructor(private readonly prisma: PrismaService) {}

  // User-scoped history powers the quests page while keeping persistence details inside the backend.
  async listHistoryForUser(
    userId: number,
    query: GetQuestHistoryQueryDto,
  ): Promise<QuestHistoryResponseDto> {
    const dayLimit = normalizeDayLimit(query.dayLimit);
    const dayOffset = normalizeDayOffset(query.dayOffset);

    // First fetch unique quest days so pagination remains day-based instead of row-based.
    const questDays = await this.prisma.dailyQuest.findMany({
      where: { userId },
      select: {
        questDateUtc: true,
      },
      distinct: ['questDateUtc'],
      orderBy: {
        questDateUtc: 'desc',
      },
    });
    const pagedQuestDays = questDays
      .slice(dayOffset, dayOffset + dayLimit)
      .map((entry) => entry.questDateUtc);
    if (pagedQuestDays.length === 0) {
      return {
        quests: [],
        hasMore: false,
        nextDayOffset: null,
      };
    }

    const rows = await this.prisma.dailyQuest.findMany({
      where: {
        userId,
        questDateUtc: {
          in: pagedQuestDays,
        },
      },
      include: {
        module: {
          select: {
            title: true,
          },
        },
      },
      orderBy: [{ questDateUtc: 'desc' }, { id: 'asc' }],
    });

    const nextOffset = dayOffset + dayLimit;
    const hasMore = nextOffset < questDays.length;

    return {
      quests: rows.map((row): QuestHistoryItemDto => {
        return {
          id: row.id,
          moduleId: row.moduleId,
          moduleTitle: row.module.title,
          // Quest type values are generated by backend rules and are constrained by shared contracts.
          type: row.type as QuestType,
          expGranted: row.expGranted,
          isCompleted: row.isCompleted,
          // Date-only format keeps frontend grouping deterministic for UTC-day history.
          questDateUtc: row.questDateUtc.toISOString().slice(0, 10),
          generatedAt: row.generatedAt.toISOString(),
          completedAt: row.completedAt ? row.completedAt.toISOString() : null,
        };
      }),
      hasMore,
      nextDayOffset: hasMore ? nextOffset : null,
    };
  }

  create(createDailyQuestDto: CreateDailyQuestDto) {
    return this.prisma.dailyQuest.create({ data: createDailyQuestDto });
  }

  findAll() {
    return this.prisma.dailyQuest.findMany();
  }

  async findOne(id: number) {
    return this.getOrThrow(id);
  }

  async update(id: number, updateDailyQuestDto: UpdateDailyQuestDto) {
    await this.getOrThrow(id);
    return this.prisma.dailyQuest.update({
      where: { id },
      data: updateDailyQuestDto,
    });
  }

  async remove(id: number) {
    await this.getOrThrow(id);
    return this.prisma.dailyQuest.delete({ where: { id } });
  }

  private async getOrThrow(id: number) {
    const record = await this.prisma.dailyQuest.findUnique({ where: { id } });
    if (!record) {
      throw new NotFoundException(`DailyQuest ${id} not found`);
    }
    return record;
  }
}

function normalizeDayLimit(value: number | undefined): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    return DEFAULT_DAY_LIMIT;
  }
  return Math.max(1, Math.min(31, Math.floor(value)));
}

function normalizeDayOffset(value: number | undefined): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    return DEFAULT_DAY_OFFSET;
  }
  return Math.max(0, Math.floor(value));
}
